### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by fajusto** [Platane/snk#10]
The dark mode only works while using Firefox. I'd appreciate if it worked on Chrome...

**Comment by Platane** [comment]
The svg uses a media query to detect dark mode 
```css
@media (prefers-color-scheme: dark) { 
```
( I took the idea from https://github.com/jamiebuilds/dark-mode-github-readme-logos )

This media query is set by either browser settings, or OS settings. 

Github seems to respect this params, but you can overwrite it in the [/settings/appearance](https://github.com/settings/appearance) page. This one we can not detect with css afaik.

As a result, it works if you set your OS or browser theme to dark, but not if you force the theme on github appearance setting. 

I don't know any solution for that, if you know some, I am very interested to hear it :+1:

**Comment by Platane** [comment]
Here is a thread discussing a way to have light / dark image in readme 

https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/59

So far nothing concrete as you can see
