### ISSUE TITLE
Private repo contributions are not included after update to V3. 

### ISSUE THREAD

**Issue by harrisadni** [Platane/snk#105]

**Comment by Platane** [comment]
I think you can configure that on your profile page

![image](https://github.com/Platane/snk/assets/1659820/16c66b46-2295-4787-8e8b-a2a548bcc1d1)

can you confirm ?

**Comment by harrisadni** [comment]
Confirmed private contribution option is checked.

Below is how my contribution looks like. (Private contribution checked)
![image](https://github.com/Platane/snk/assets/80310509/a4eb71d4-5de4-414e-9990-cb8a6c682c64)

And here is how the generated snk v3 looks like. Missing all of the private contributions.
![image](https://github.com/Platane/snk/assets/80310509/dc936cd8-fc47-4b64-98a1-a3d7a39be287)

**Comment by Vinfall** [comment]
Maybe you are misled as GitHub calculates XXX contributions in last year based on **past 365 days**, _not_ all of them are really contributed in 2023. Does the online demo preview above matches the contribution graph when you check `2023` in Contribution activity?

**Comment by Jirafey** [comment]
What is the fix for that? I keep getting notifications about it failing.

**Comment by harrisadni** [comment]
ISSUE RESOLVED after updating my actions to use **Platane/snk@v3.2.0**
![image](https://github.com/Platane/snk/assets/80310509/6f7bcced-7750-4ef7-bcdb-f8adb00f475e)

**Comment by harrisadni** [comment]
> What is the fix for that? I keep getting notifications about it failing.

Probably need to update to use snk@v3.2.0
