### ISSUE TITLE
Why is the generated data different from mine? 

### ISSUE THREAD

**Issue by sishen654** [Platane/snk#107]
yml config:
![image](https://github.com/Platane/snk/assets/65691266/2e876d10-7607-42bc-a51b-60a67c23e584)

![image](https://github.com/Platane/snk/assets/65691266/21e051d0-b56d-40cf-bb15-3b59e48adaee)
![image](https://github.com/Platane/snk/assets/65691266/e4f529c5-7948-47fb-9fc7-0a4e63669606)

**Comment by Platane** [comment]
it's something you can config from your github profile page 

![image](https://github.com/Platane/snk/assets/1659820/f4a72a1c-6351-4f90-91bb-69382a2683f9)

**Comment by sishen654** [comment]
> it's something you can config from your github profile page
> 
> ![image](https://user-images.githubusercontent.com/1659820/280462737-f4a72a1c-6351-4f90-91bb-69382a2683f9.png)

Thanks for you answer❤️
