### ISSUE TITLE
Accreditation

### ISSUE THREAD

**Issue by xinthose** [Platane/snk#109]
Hello.  Thank you for your nice repository, it works well.  
I am surprised you do not mention giving your repository proper credit (I think you used to).  Is this text below the SVG icon fine?

```html
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/xinthose/xinthose/output/github-contribution-grid-snake-dark.svg" />
  <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/xinthose/xinthose/output/github-contribution-grid-snake.svg" />
  <img alt="github-snake" src="github-snake.svg" />
</picture>
<br />
<em>
  Generated with
  <a href="https://github.com/Platane/snk">
    Platane/snk
  <a/>
</em>
```

**Comment by Platane** [comment]
Hi thanks :)

You can link the repository. It's very nice but I don't require it.

There is also a [description tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc) in the generated svg. But I don't think it is noticed a lot.
