### ISSUE TITLE
How to disable dark background. 

### ISSUE THREAD

**Issue by hoc081098** [Platane/snk#11]
Thanks for your work.
On Chrome Window 10, Dark Mode. Image is like
![image](https://user-images.githubusercontent.com/36917223/125505605-92625181-f6ba-4a5f-8e03-67917e166e72.png)
How to disable dark background of image. Thanks

**Comment by Platane** [comment]
Hi @hoc081098 
Since this image is meant to be embed in github, it follows github dark mode theme.

If you don't want that you can manually remove the media query inside the svg file.

**Comment by hoc081098** [comment]
> Hi @hoc081098
> Since this image is meant to be embed in github, it follows github dark mode theme.
> 
> If you don't want that you can manually remove the media query inside the svg file.

Thanks
