### ISSUE TITLE
[Feature] - Add ability to hide progress bar

### ISSUE THREAD

**Issue by genzzo** [Platane/snk#114]
Can we add an option to hide the progress bar at the bottom?

**Comment by Platane** [comment]
I am not accepting feature request for this project. But feel free to fork it if you want to change the behaviour

**Comment by ArthurLobopro** [comment]
@Platane I made it ![here](https://github.com/ArthurLobopro/snk). If you thing I need to change something like adding credits (I will do it later anyway, but if want to say me how) tell me please.

@genzzo You can use `ArthurLobopro/snk/svg-only@v0` workflow and pass `hide_stack=true` in the query params to hide the progress bar

**Comment by Platane** [comment]
good job !

**Comment by genzzo** [comment]
@ArthurLobopro thank you!
Just a quick note that your readme file documents the action as `ArthurLobopro/svg-only@v0` while it should be `ArthurLobopro/snk/svg-only@v0`

**Comment by ArthurLobopro** [comment]
@genzzo Thank you, I will fix it right now!
