### ISSUE TITLE
Any chance we could get this to work with gitea runners/accounts for self hosted as well?

### ISSUE THREAD

**Issue by Crelex** [Platane/snk#115]
Thing is really cool -- I didn't even realize an SVG could be animated..

**Comment by Platane** [comment]
I don't know gitea runners, but I think it should be possible.

Here is the functions used to (1) fetch the contribution graph (requires a valid github token to query the rest API)  (2) generates the files (either gif with some native dependencies, or svg without dependencies )  

https://github.com/Platane/snk/blob/main/packages/action/generateContributionSnake.ts#L9
