### ISSUE TITLE
Snk doesn't work on my profile

### ISSUE THREAD

**Issue by voxten** [Platane/snk#119]
I'm getting this kind of output image, nothing is animating, nothing is changing. Only thing that appears is snake, but he's static and doesn't move at all.
![image](https://github.com/Platane/snk/assets/52979294/cfb65d87-36ee-438a-a362-4ce941df5d19)

**Comment by Platane** [comment]
it seems like you are using https://github.com/aelassas/snk

Do you have the same issue using this action ? otherwise it should be reported to aelassas/snk

**Comment by voxten** [comment]
I have changed to your setup and now everything works. Thanks a lot!
