### ISSUE TITLE
Hello, Can i ask some question?

### ISSUE THREAD

**Issue by mynameisjinhohong** [Platane/snk#126]
hello, i'm junior programmer in korea.
Now, i use this snake for my github profile. I want to say thank you for make this repo.
But, I think my github contribute not match with this repo.
<img width="760" alt="스크린샷 2024-08-06 오전 9 58 09" src="https://github.com/user-attachments/assets/26d27a29-67f5-4de0-a8f7-e9a5b5866cec">
this is my contribute in my profile.
<img width="883" alt="스크린샷 2024-08-06 오전 9 58 18" src="https://github.com/user-attachments/assets/b23989cc-beda-425f-b1a0-be1d73fbfc33">
this it my contribute in [platane.github.io/snk](https://platane.github.io/snk). this is not match in my real contribute
My github profile make same svg in that site. i want to know why it happen

PS.
<img width="927" alt="스크린샷 2024-08-06 오전 10 07 02" src="https://github.com/user-attachments/assets/6859a5bf-6ace-4faa-85d6-5aa1af3e7101">
I tried to chek on,off in contribute setting but nothing change....

**Comment by Platane** [comment]
thanks !

regarding the contributions, it should match your settings. There might be a delay where the github api (used to generate the animation) uses the previous settings.

I am checking now and it seems that it matches for your profile
