### ISSUE TITLE
Unable to display year, month, day, and hover effect on snake animation

### ISSUE THREAD

**Issue by GAURAV07C** [Platane/snk#127]
I'm using the Platane/snk GitHub Action to generate a snake animation for my GitHub contribution graph. I've added the year=true, month=true, day=true, and tooltip=true parameters to the with section to display the year, month, day, and hover effect on the x-axis. However, these features are not displaying as expected.

Code:

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_bg=#24292e&year=true&month=true&day=true&tooltip=true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add dist/
          git commit -m "Update snake files"
          git push origin main
Steps to reproduce:

I modified the GitHub Action code to include the year=true, month=true, day=true, and tooltip=true parameters.
I committed and pushed the changes to my repository.
The snake animation is not displaying the year, month, day, and hover effect as expected.
Expected behavior:

The snake animation should display the year, month, day, and hover effect on the x-axis.

Actual behavior:

The snake animation is not displaying the year, month, day, and hover effect.

Additional information:

GitHub repository URL: https://github.com/GAURAV07C/GAURAV07C
GitHub Action code: https://github.com/GAURAV07C/GAURAV07C/blob/main/.github/workflows/generate-snake.yml
Please help me troubleshoot this issue!

**Comment by Platane** [comment]
those options are indeed not supported
