### ISSUE TITLE
Is it possible to generate snake.svg on the master/main branch?

### ISSUE THREAD

**Issue by Tarun-Kamboj** [Platane/snk#13]

**Comment by Platane** [comment]
As you can see from the github [workflow file](https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml)

Generating the snake.svg file is the only think that the action does. What you do with the file is up to you.
In the example I use [ghaction-github-pages](https://github.com/marketplace/actions/github-pages) to commit the file to a special branch. But you could do anything, such as uploading the file to a third party service. 

You can probably push a new commit to the master branch, using for example this [add-commit](https://github.com/marketplace/actions/add-commit) action.

I personally prefer to keep my master branch free of automatic commit.
