### ISSUE TITLE
not able to give the date range, 

### ISSUE THREAD

**Issue by mayureshzende** [Platane/snk#130]
how can we pass the date range or year to fetch the contribution of the user, I am trying to pass parameters, as what is given in the file 

**\snk\packages\github-user-contribution\index.ts**

 * @param userName github user name
 * @param options
 *
 * @example
 *  getGithubUserContribution("platane", { from: "2019-01-01", to: "2019-12-31" })
 *  getGithubUserContribution("platane", { year: 2019 })

here is my action.yml : https://github.com/mayureshzende/name-graph/blob/master/.github/workflows/main.yml

but for me this is not working, can you please help in setting that in the action.yml file to get that for the specific year, 
thanks :)

**Comment by Platane** [comment]
this option is not supported.

It could be added but I am not investing a lot of time on this project at the moment.

**Comment by mayureshzende** [comment]
thanks for the reply, cool, but will be great that we can add the timeline to get the graph.
