### ISSUE TITLE
Need help pls🤖

### ISSUE THREAD

**Issue by MackDing** [Platane/snk#132]
Hi there, my friends and I really like your project, but it hasn't been working properly lately. Please take some time to check it, thank you !🤩 If we could update the README again, that would be even better🍟

**Comment by Platane** [comment]
it seems to work just fine in your repository:

https://raw.githubusercontent.com/mackding/mackding/output/github-contribution-grid-snake.svg
![](https://raw.githubusercontent.com/mackding/mackding/output/github-contribution-grid-snake.svg)
