### ISSUE TITLE
Generated game doesn't seem to be correct

### ISSUE THREAD

**Issue by tails618** [Platane/snk#133]
I might be misunderstanding something, but the graph that's generated in the gif doesn't seem to line up with my actual graph. Here's what's generated:
<img width="862" alt="Screenshot 2024-10-09 at 10 21 30 PM" src="https://github.com/user-attachments/assets/a7c8b041-097c-484d-8ced-8ab9b36177b2">
And here's my actual graph
<img width="763" alt="Screenshot 2024-10-09 at 10 22 16 PM" src="https://github.com/user-attachments/assets/ff2df4b6-87c0-45b3-a959-5047408106ca">
The snake graph has a lot more green than my actual graph. Why is this?

**Comment by caiofmbarbosa** [comment]
i'm with the same problem

**Comment by Platane** [comment]
I think you changed the contribution setting
![image](https://github.com/user-attachments/assets/2f6999dc-299d-461b-ace1-280dfb404a86)


I regenerated your snake animation and it reflect the setting change now:
![image](https://github.com/user-attachments/assets/223f5a7b-3130-4338-98dc-6d3581d3acfd)


related #https://github.com/Platane/snk/issues/107

**Comment by tails618** [comment]
I have both of those on - I'm not sure if that's correct but it doesn't seem to match no matter how they're set. The animation still seems to have far more contributions than real life, and doesn't match what you show in your screenshot of my animation:

<img width="880" alt="image" src="https://github.com/user-attachments/assets/9865c0bc-1466-4cd2-aab1-7fab3d5dfcc0">

**Comment by TechnologyHell** [comment]
AFAIK, it does depend on the contributions appearance settings.
The private contributions is supposed to show up on the contributions graph if you set it to on. And if turned on, the workflow will try to access both - public + private contributions.
By default, the workflow is supposed to count on the public contributions only.

**Comment by Platane** [comment]
@tails618 I just checked and you linked to my generated svg : https://github.com/tails618/tails618/blob/main/README.md?plain=1#L14-L16 

yours is in your repository on that branch : https://github.com/tails618/tails618/blob/output/github-contribution-grid-snake.svg

and it's accessible at that url : [https://raw.githubusercontent.com/**tails618**/**tails618**/output/github-contribution-grid-snake.svg](https://raw.githubusercontent.com/tails618/tails618/output/github-contribution-grid-snake.svg)

**Comment by Platane** [comment]
@tails618 I think I answered you, can I close this?
