### ISSUE TITLE
Snake is allowed to leave GitHub?

### ISSUE THREAD

**Issue by j6k4m8** [Platane/snk#18]
It appears that the snake is allowed to leave the seven-day width at times:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/693511/151706278-1a9c012c-9ecf-4eb0-8e89-f1cd1717d8ba.png"> <img width="600" alt="image" src="https://user-images.githubusercontent.com/693511/151706299-7ff76237-0688-4337-88e1-1bccfa213a10.png">

Is this expected behavior? My expectation would be that the snake remains within the "arena" but I don't have particularly strong feelings about it :)

Fun tool! Thank you for sharing it!

**Comment by j6k4m8** [comment]
On closer inspection, I wonder if this is to make it possible to get a solution to the maze-solve that allows the snake to sort by square-type (?)

**Comment by Platane** [comment]
Ah yes I decided that it looks better that way :smile: 

The algorithm does its best to eat the lighter square first. Notice that it's not always possible to strictly do so ( if a light square in enclosed inside darker one basically ) 

Thanks for the interest in the project :+1:
