### ISSUE TITLE
[feature] changing colors on snek

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [Platane/snk#22]
so yes currently snek is purple on white squares. i want snek to be blue-yellow on dark-grey squares. when it'll be possible? (wanna do that cause i oftenly code in python and didnt wanted to make language cards ;p)

+ i wanna save green contrib squares •w• this yes is cool

**Comment by Platane** [comment]
There is currently no option to force a color palette from the github action. And I don't plan to add it to avoid ending up with a lot of options.

However you can either

- fork the repo and create your own action, the relevant code is [here ](https://github.com/Platane/snk/blob/master/packages/action/generateContributionSnake.ts#L19-L32)

- search and replace the color code in the resulting svg file.

**Comment by hacknorris-aka-penguin** [comment]
means - what if it'd be non-default option? means - user didnt needed to set it up (it'd take default colors like are now) but if someone would it could pass some arguments?

**Comment by Platane** [comment]
By default it uses the color palette that github uses. And it cannot be changed at the moment.
