### ISSUE TITLE
Can you make a dark theme version?

### ISSUE THREAD

**Issue by Johann-Goncalves-Pereira** [Platane/snk#25]
I love this project, but It would be great if It has a dark Theme. Because I fill a little alt of place in this image.

![image](https://user-images.githubusercontent.com/62612685/162645144-16595b01-cd4f-4cf2-9813-b6e41a45237a.png)

**Comment by Platane** [comment]
It already switch to the dark theme palette on this css selector `@media (prefers-color-scheme: dark)`. Which works when the os force a dark mode, but not when it's set from github settings. I does work when I switch my android phone to dark mode for example.

However, I saw that [this issue](https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/77) got resolved. Which allows to have one image url for dark mode, and one for light. ( yay ! )

I need to think of a good option to generate two (or more) svgs with different color palette.

**Comment by Platane** [comment]
I published a new (beta) version, which supports multiple outputs with different rendering options.

And I updated my readme to use the dark mode version conditionally : https://github.com/Platane

I am not sure about the new option convention, I might change it,

**Comment by billyeatcookies** [comment]
Dark theme is available and is working perfectly :)
![image](https://user-images.githubusercontent.com/70792552/164497251-bce6755a-f1c3-45a2-b8bc-a55474856bc4.png)

**Comment by Johann-Goncalves-Pereira** [comment]
@Platane Thanks man, I love it.

This is my custom Svg, and I try to follow the colors on the default GitHub.

`dist/github-snake-custom.svg?color_snake=#4489ec&color_dots=#2d333b,#14482e,#067238,#2dab47,#38d353`

![image](https://user-images.githubusercontent.com/62612685/164949634-65cf9efd-c8ab-4111-b629-dd9108a574e9.png)
