### ISSUE TITLE
Add supported query string options to README

### ISSUE THREAD

**Issue by billyeatcookies** [Platane/snk#29]
## Description
Supported query string options that can be used in the script are listed in [action.yml](https://github.com/Platane/snk/blob/main/action.yml), but this is not noticed most of the time. 
Instead it should be listed in the README.md or a new doc dedicated to the usage and instructions.

https://github.com/Platane/snk/blob/8f1481341a208bfa0ed284cefb50ae8352343dff/action.yml#L21-L25

**Comment by Platane** [comment]
Done ! thanks for the feedback again
