### ISSUE TITLE
When running workflow, generates following error

### ISSUE THREAD

**Issue by hashfx** [Platane/snk#33]
Generates following annotation
Action failed with **"Cannot find module 'canvas' Require stack: - /home/runner/work/_actions/Platane/snk/v2/svg-only/dist/index.js"**

_Snapshot attached for reference_

![snakeError](https://user-images.githubusercontent.com/69109482/171424449-10d87afd-daff-4a4e-99a6-4261fcccde68.JPG)

**Comment by Platane** [comment]
You need to run the action "platane/snk@v2"

The one you are using ( "platane/snk/svg-only@v2" ) cannot generate gif images

**Comment by hashfx** [comment]
Thank you very much @Platane, it worked😄
