### ISSUE TITLE
Suggestion: Add user to push

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [Platane/snk#38]
Allow us to add an option like: `USER` which where we put a PAT token and instead of the default GitHub Actions bot pushing the svg, the other user will.

Like:
`WilliamDavidHarrison pushed github-contribution-grid-snake.svg to output branch`

Instead of:
`github-actions[bot] pushed github-contribution-grid-snake.svg to output branch`

Sorry if this isn't well explained.

**Comment by WilliamDavidHarrison** [comment]
@Platane what do you think?

**Comment by Platane** [comment]
This action only generate the file in the runner File S.mystem.

As an example I do indeed use another action to push it to the output branch. But this is out off this repository scope.

I think you should look into ghactions-github-pages if this kind of option is supported, or use another action
