### ISSUE TITLE
How do I adapt for Halloween?

### ISSUE THREAD

**Issue by nuhkoca** [Platane/snk#39]
Hello,

Thanks for the amazing work and I've been using it for quite a long time. I wonder if can I somehow adapt the output for Halloween colors as shown below?

<img width="785" alt="Screenshot 2022-10-31 at 01 38 45" src="https://user-images.githubusercontent.com/5719389/198910228-9f721142-7b25-455c-b919-634aeb90d654.png">

**Comment by Platane** [comment]
Hi !

You can pass options such as dot colors

example:
```yaml
outputs: |
      dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
```

( more examples in the [readme](https://github.com/Platane/snk#usage) )

It might be a bit late for Halloween though 😅

**Comment by nuhkoca** [comment]
Thank yeah 😄
