### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by Zo-Bro-23** [Platane/snk#49]
snk doesn't seem to be working - Any GitHub profile that used to have a snake contribution grid now shows this:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/62234360/204982270-5f97360f-1a04-4d0b-9bc3-6c0a6d40ee48.png">

*Any GitHub Profile* includes, unfortunately, yours. In fact, the screenshot is from [your profile](https://github.com/Platane).

There are two explanations. Either snk stopped working, or this has something to do with my setup (browser, PC, etc). Since there are no recent commits, maybe an update to GitHub Actions broke the code. If you are able to see the animation though, the issue is at my end. I tried with a Mac, PC, and an Android phone, and none of them show the animation. Maybe it has something to with my ISP, but I doubt it. Kindly let me know if you have the same issue, or what you think could be the issue. Thanks!

**Comment by Zo-Bro-23** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/62234360/205043264-3a005ae6-f003-45b0-8a17-7f8d1d16bd43.png">
Network tab

It seem to show connection timed out, which is what I've experienced when I tried to open the image url in a new tab.

Debugging further, the issue seems to be persistent with all raw.githubusercontent.com URLs. Moreover, my phone on mobile data shows the raw content while my phone on WiFi doesn't. Investing, I found [this](https://www.reddit.com/r/india/comments/n3b9jc/jiofiber_blocked_access_to_rawgithubusercontentcom/) Reddit post which explains many users of the same ISP as me complaining about this domain being blocked.

Any suggestions on what I can do? Maybe it's fine since my README loads well for others. GitHub Actions seem a bit cumbersome to setup, since I don't know anything about them, so would it be possible to move to a different setup? Maybe a serverless setup where the Action just has to do a cURL run to render the image on the server? Let me know if you have any suggestions for me! Thanks for your help 🙃

**Comment by Platane** [comment]
Ah I see, sorry about that.

This action is only concern with producing a svg ( or gif ) file in the github action runner. I do recommend to then use github branch to serve the image since it seems convenient. 
Since this is not great for you, you could use another image hosting provider. This action could be of interest : [publish-on-imgur](https://github.com/marketplace/actions/publish-on-imgur) It does require an account, so it's not as trivial.
