### ISSUE TITLE
Error: Action failed with "Cannot read property 'trim' of undefined"

### ISSUE THREAD

**Issue by GuillaumeFalourd** [Platane/snk#5]
Hi @Platane , and thank you for developing and sharing this snake svg/gif repository 🚀  

I got this error since morning when executing the daily github actions workflow of my profile:

```Run Platane/snk@master
/usr/bin/docker run --name platanesnklatest_4dfa34 --label 442333 --workdir /github/workspace --rm -e INPUT_GITHUB_USER_NAME -e INPUT_SVG_OUT_PATH -e INPUT_GIF_OUT_PATH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/GuillaumeFalourd/GuillaumeFalourd":"/github/workspace" platane/snk:latest
🎣 fetching github user contribution
Error: Action failed with "Cannot read property 'trim' of undefined"
```

![error snake workflow](https://user-images.githubusercontent.com/22433243/106927601-188d5880-66f1-11eb-8381-39a245fe7598.png)

Any idea about how to resolve it ? I can't say if it's something related to personal configurations or not. For what I checked online based on the error message, it seems to be related to an unchecked error. But as I'm not familiar with TypeScript, I prefer opening this ISSUE to get some insights.

**Comment by Platane** [comment]
Hey man thanks for using this project, I appreciate :+1: 

I got the issue for my action as well. I didn't get the time to dive into it.
The script crawls the html of the github profile page to get the grid, which is unfortunate because it tends to break often when they update the page ( which happens quite frequently )

I think I should have the time to fix that after work

**Comment by GuillaumeFalourd** [comment]
I don't know exactly how you did it, but there may be a way to extract those datas without crawling the html, using directly the github/users url. 

Example: 
https://github.com/users/GuillaumeFalourd/contributions
https://github.com/users/Platane/contributions

I extracted it from the source_page:

```
<div class="js-calendar-graph mx-md-2 mx-3 d-flex flex-column flex-items-end flex-xl-items-center overflow-hidden pt-1 is-graph-loading graph-canvas ContributionCalendar height-full text-center days-selected" data-graph-url="/users/GuillaumeFalourd/contributions?to=2021-02-04" data-url="/GuillaumeFalourd" data-from="2020-02-02 00:00:00 -0300" data-to="2021-02-04 23:59:59 -0300" data-org=""></div>
```

**Comment by Platane** [comment]
I think I tried that, but for some reason it's not a sliding window for the current year. So it doesn't match the chart you get when you first land on the profile page.
Anyway it seems like it follows the same markup, so it will probably be broken the same way :(

**Comment by Platane** [comment]
https://github.com/Platane/snk/commit/17b852aab506fcaf6e199d86aeb4146bca695208 fixes it :)
