### ISSUE TITLE
Actions + Interactive Website Not Working

### ISSUE THREAD

**Issue by Zo-Bro-23** [Platane/snk#54]
![image](https://user-images.githubusercontent.com/62234360/210915946-2e423161-7a1c-4344-aaf7-d30eca1c4831.png)

The screenshot is from the Actions tab of your profile repo. A similar error shows up on my workflows too. The interactive website just says: "error :("

Kindly let me know what the issue is and how I can fix it (I'm assuming one of the libraries or frameworks you use changed). Thank you.

**Comment by Platane** [comment]
It seems that github changed the markup for the profile page.

The parser failed to grab the grid

I fixed that in 2.2.0

Thanks for reporting all :+1:
