### ISSUE TITLE
svg file ruined 

### ISSUE THREAD

**Issue by AmirMGhanem** [Platane/snk#57]
Can anyone tell me why i am getting as output only small piece of the snake svg ? 

https://github.com/AmirMGhanem/AmirMGhanem/blob/output/github-contribution-grid-snake.svg

* it worked before, today's workflow went like this.

@Platane

**Comment by Zxilly** [comment]
You use `Platane/snk@master`, just switch it to `uses: Platane/snk@main`
Github just change their profile page structure. The outdated version no longer work.

**Comment by AmirMGhanem** [comment]
@Zxilly

**Comment by AmirMGhanem** [comment]
BTW, 
also yours  @ https://github.com/Zxilly/Zxilly

**Comment by Zxilly** [comment]
I just update it, it works now.
You can follow my conf.

**Comment by Platane** [comment]
Thanks for the help @Zxilly 

For some context, I was lazy with the versioning when I started. I did not pin the version in my workflow config. 

As a lot of people copied my config, this lead to a lot of workflows automatically pulling the latest version. Which is a pain when introducing breaking changes.

When I introduced the v2 ( with breaking change ) I left the master version frozen to not impact them.

Unfortunately, today github changed the profile page markup, I fixed it on 2.2.0 . But master is frozen

**Comment by Zxilly** [comment]
Maybe this fix can be backport to old version.

**Comment by Platane** [comment]
> Maybe this fix can be backport to old version.

yes, I think it needs to

**Comment by AmirMGhanem** [comment]
Thank you! 
works as Expected 
@Zxilly 

Thanks @Platane :)
