### ISSUE TITLE
[Feature] Pertaining to the shape of a snake

### ISSUE THREAD

**Issue by ramazansancar** [Platane/snk#61]
I created the code for the triangle svg drawing. However, I have no idea how to proceed. Can you help me?

> https://github.com/ramazansancar/snk_readme/blob/main/packages/types/point.ts#L10

```ts
export const aroundTriangle = [
  { x: 1, y: 0 },
  { x: -1, y: -1 },
  { x: -1, y: 1 },
] as const;
```

**Comment by Platane** [comment]
The [around4](https://github.com/Platane/snk/blob/main/packages/types/point.ts#L3-L8) const is used to iterate over all directions. It's used in several places to traverse the grid. I don't think it does what you think.

What do you want to achieve ?

**Comment by ramazansancar** [comment]
> The [around4](https://github.com/Platane/snk/blob/main/packages/types/point.ts#L3-L8) const is used to iterate over all directions. It's used in several places to traverse the grid. I don't think it does what you think.
> 
> What do you want to achieve ?

I want to make the square shape of the snake triangular.

**Comment by Platane** [comment]
Ok, then you might want to look at https://github.com/Platane/snk/blob/main/packages/svg-creator/snake.ts ( for svg rendering )
