### ISSUE TITLE
why is the grid black

### ISSUE THREAD

**Issue by shikingram** [Platane/snk#65]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/43238749/221125709-4b7b9b5e-4801-493b-b82f-0c0bff1b6767.png">

🧐🧐🧐🧐

**Comment by noobie7** [comment]
Hey, I'd like to assign this to myself, who do I ask?

**Comment by Platane** [comment]
The is a media-query which test for `prefers-color-scheme` which is set by the browser.

I am guessing that your browser set this flag, but your github account is configured to ignore it and use light mode (?)

github supports a safer way to detect the theme via the [picture element](https://github.com/Platane/snk#usage). I am going to use it in this readme too.

Could you tell me what you see on this page https://github.com/Platane/Platane ? I might need to disable the unreliable prefers-color-scheme media query

**Comment by Platane** [comment]
I fixed it in [v2.2.1](https://github.com/Platane/snk/releases/tag/v2.2.1)  let me know if that does it for you

**Comment by ziadOUA** [comment]
Yup, I also had this issue. I fixed it by using the `<picture> </picture>` tags.
