### ISSUE TITLE
Is there a way to only count commits for a specific repository instead of a specific user?

### ISSUE THREAD

**Issue by alanhg** [Platane/snk#70]

**Comment by Platane** [comment]
I don't think so. Currently it read the data from the html page at https://github.com/alanhg

However, you could generate the grid yourself (by querying the github rest API for example) , and use

```ts

const grid = userContributionToGrid(cells);
const snake = snake4;

const chain = getBestRoute(grid, snake)!;

createSvg(grid, cells, chain, drawOptions, animationOptions);
        
```

from https://github.com/Platane/snk/blob/main/packages/action/generateContributionSnake.ts#L9-L51
