### ISSUE TITLE
CORS error when trying to embed svg in Github Pages website

### ISSUE THREAD

**Issue by salesp07** [Platane/snk#71]
Is there a way to do that, or we can only have it in the github readme?

**Comment by Platane** [comment]
The script is only concerned with generating the image, it is up to you to host it where is fits your need.

However the solution I chose ( storing it on a github branch ) should work, as content from raw.githubusercontent.com do have the header `Access-Control-Allow-Origin:*`

**Comment by salesp07** [comment]
Right... I hadn't noticed the output branch and was fetching from github blob. Awesome repo and thx for the response!
