### ISSUE TITLE
Error in GitHub Action

### ISSUE THREAD

**Issue by ninpl** [Platane/snk#74]
Error: Action failed with "Cannot read properties of undefined (reading 'split')"

**Comment by ninpl** [comment]
[platane.github.io/snk](https://platane.github.io/snk) also throws an error.
![Captura de pantalla 2023-07-15 032735](https://github.com/Platane/snk/assets/7427480/68af83b1-ca6a-481a-af76-6515d638abe8)

**Comment by milaabl** [comment]
Same error! Worked fine yesterday.

**Comment by gregWDumont** [comment]
Same here, thanks for the good work!

**Comment by Isabe1le** [comment]
PR https://github.com/Platane/snk/pull/76 Appears to be trying to fix this issue.
@milaabl mentioned that more help may be needeed to fix this. https://github.com/Platane/snk/pull/76#issuecomment-1636745123

**Comment by aelassas** [comment]
Issue fixed. Check out my pull request: https://github.com/Platane/snk/pull/77

**Comment by atom-tr** [comment]
Nice. ^^

**Comment by marcokreeft87** [comment]
If only the developer would respond..

**Comment by Platane** [comment]
#75
