### ISSUE TITLE
The workflow didn't work as intended.

### ISSUE THREAD

**Issue by MarkCay** [Platane/snk#81]
Hi, I've been using the workflow on my GitHub repository for months already, but earlier, I experienced an issue about the workflow's SVG output. 

Here is my workflow's code: https://github.com/MarkCay/MarkCay/blob/main/.github/workflows/main.yml

Below is the SVG output:
![github-contribution-grid-snake (1)](https://github.com/Platane/snk/assets/44314383/521bbad3-24aa-4db0-b678-76fca391b0b2)

**Comment by GuhSoares** [comment]
use this code in your main.yml

name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: YOUR NAME
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by GoudronViande24** [comment]
Look at the [latest release](https://github.com/Platane/snk/releases/tag/v3.0.0), there is a breaking change. You probably were using the master branch for your workflow and so it broke as soon as the new version released.

**Comment by jasonycw** [comment]
Just update the step to this https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml#L25-L33

And then update the README file like this https://github.com/Platane/Platane/blob/master/README.md?plain=1#L1-L5

**Comment by MarkCay** [comment]
Thank you very much!
