### ISSUE TITLE
Blue dots

### ISSUE THREAD

**Issue by Benhrpr** [Platane/snk#84]
This happens when I run the code, any ideas on how to fix this?

<img width="116" alt="image" src="https://github.com/Platane/snk/assets/137661756/d2c4eae0-f715-4c01-84cc-613fbf0414a5">

**Comment by CihatKOCAK** [comment]
i have the same problem in green :')

**Comment by CihatKOCAK** [comment]
I updated the yml file and changed the inclusion method on the md side, it works fine now, 

myYML -> https://github.com/CihatKOCAK/CihatKOCAK/blob/main/.github/workflows/main.yml 

and

myMD -> https://github.com/CihatKOCAK/CihatKOCAK/blob/main/README.md

you can browse and set

**Comment by Platane** [comment]
you need to update to the v3 version

check the readme for the up to date code snippet
