### ISSUE TITLE
service died

### ISSUE THREAD

**Issue by zlaazlaa** [Platane/snk#85]
Hi, I notice that my snake workflow not work well, is there any problem?
My action return green icon,  see here -> https://github.com/zlaazlaa/zlaazlaa/actions/runs/5675308603
but the gif is broken, see here -> https://github.com/zlaazlaa/zlaazlaa/blob/main/assets/github-contribution-grid-snake.gif

**Comment by zlaazlaa** [comment]
the service is good before two weeks ago, but now the snake become like this
![image](https://github.com/Platane/snk/assets/72907523/eb952f5d-049a-4f4d-b366-6e06a1c006ed)

**Comment by zlaazlaa** [comment]
I got it!
Problem come from UPDATE V3 -> https://github.com/Platane/snk/commit/aebc3a92857730857d5a96010a3538f16bbec662
In V3, we have to use GITHUB_TOKEN to generate action, so the old workflow not work.
We can use new workflow in @Platane Repo: https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml
Also, V3 change the picture location from repo to Github CDN. So, profile README.md also need to change, like https://github.com/Platane/Platane/blob/master/README.md
The picture url is like https://raw.githubusercontent.com/platane/platane/output/github-contribution-grid-snake-dark.svg. **platane need to be changed with your GitHub ID.**
Finally, Thanks @Platane , I love this project.

**Comment by Platane** [comment]
yep exactly :+1:

**Comment by billyeatcookies** [comment]
thank you for opening this issue @zlaazlaa and thank you @Platane for the awesome project! ❤

**Comment by Mickeyyyang** [comment]
> I got it! Problem come from UPDATE V3 -> [aebc3a9](https://github.com/Platane/snk/commit/aebc3a92857730857d5a96010a3538f16bbec662) In V3, we have to use GITHUB_TOKEN to generate action, so the old workflow not work. We can use new workflow in @Platane Repo: https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml Also, V3 change the picture location from repo to Github CDN. So, profile README.md also need to change, like https://github.com/Platane/Platane/blob/master/README.md The picture url is like https://raw.githubusercontent.com/platane/platane/output/github-contribution-grid-snake-dark.svg. **platane need to be changed with your GitHub ID.** Finally, Thanks @Platane , I love this project.

thanks!
