### ISSUE TITLE
Cannot link output to readme file

### ISSUE THREAD

**Issue by arjunindia** [Platane/snk#86]
the output url seems to have the commit ID in it, and the url https://raw.githubusercontent.com/[user]/[user]/output/github-contribution-grid-snake-dark.svg doesn't seem to work

**Comment by Platane** [comment]
https://raw.githubusercontent.com/arjunindia/arjunindia/output/github-contribution-grid-snake-dark.svg works no?

**Comment by arjunindia** [comment]
Wait what
