### ISSUE TITLE
Generate incomplete green dots

### ISSUE THREAD

**Issue by Yang-Shiqin** [Platane/snk#88]
I'm using the svg-only version, but only part of the green dots can be generated, as shown in the following figure:

![image](https://github.com/Platane/snk/assets/77830097/6c214a6b-17a9-44ae-8f80-b88222fb04cc)

But my contribution is shown in the figure below, and the two are different:

![image](https://github.com/Platane/snk/assets/77830097/50d6eab9-d645-4793-95e6-874ad1ec1204)

my yaml: [https://github.com/Yang-Shiqin/Yang-Shiqin/blob/main/.github/workflows/main.yml](https://github.com/Yang-Shiqin/Yang-Shiqin/blob/main/.github/workflows/main.yml)

**Comment by Platane** [comment]
I think you are seeing your private contribution calendar, and the action uses the public one.
When I go to your github profile, I see a contribution calendar similar to the first pic

**Comment by Yang-Shiqin** [comment]
It makes sense! Thank you for your answer!
