### ISSUE TITLE
my feedback

### ISSUE THREAD

**Issue by Andrew-devcoder** [Platane/snk#96]
Hello,

I would like to express my gratitude for your work on Snk. As a user, I wanted to share my feedback. I found it challenging to understand how to create my own commit history with Snk. To address this, I added additional lines of code to the _YML_ file, specifically:

```
- name: Clone repo
  uses: actions/checkout@v3
```

I also correctly integrated the following code into my _README_ file:

```
<picture>
  <source
    media="(prefers-color-scheme: dark)"
    srcset="https://raw.githubusercontent.com/Andrew-devcoder/Andrew-devcoder/output/github-contribution-grid-snake-dark.svg"
  />
  <source
    media="(prefers-color-scheme: light)"
    srcset="https://raw.githubusercontent.com/Andrew-devcoder/Andrew-devcoder/output/github-contribution-grid-snake.svg"
  />
  <img
    alt="github contribution grid snake animation"
    src="https://raw.githubusercontent.com/Andrew-devcoder/Andrew-devcoder/output/github-contribution-grid-snake.svg"
  />
</picture>
```

PS I'm a beginner, so please forgive me if I state the obvious.

**Comment by Platane** [comment]
Hi, thanks for the feedback !

I don't think the checkout step is necessary (?)

I have noticed that you are using the version on master ( snk@master ) which is deprecated. You can update to the v3 ( the api changed a bit, it's all documented in the readme )
