### ISSUE TITLE
The web demo doesn't work

### ISSUE THREAD

**Issue by ivan-developer-01** [Platane/snk#98]
The web demo (https://platane.github.io/snk/) doesn't work. It says "error :(":

> ![screenshot](https://github.com/Platane/snk/assets/127977316/f41afbb0-60e2-4820-8d41-d0e1f632f024)

It does so for every profile:

> ![screenshot](https://github.com/Platane/snk/assets/127977316/bb4eab02-fe89-48b4-953e-c932ea6515ee)  
> ![screenshot](https://github.com/Platane/snk/assets/127977316/44846eaa-663b-4bf3-aaf1-2164f86e5e7d)  
> ![screenshot](https://github.com/Platane/snk/assets/127977316/dd01532d-e127-49a3-9e60-7090e0565320)

Do you know how to fix this?

**Comment by ivan-developer-01** [comment]
For example, let's take `octocat`. I see that the app requests the service "https://snk-one.vercel.app" with the URL "https://snk-one.vercel.app/api/github-user-contribution/octocat".

But the service responds 500. It means... something is probably wrong with your service or with the server. I've checked that another Vercel apps (e.g. "https://github-profile-trophy.vercel.app/?username=octocat") works.

**Comment by Platane** [comment]
thanks for the report, I am looking for a fix

**Comment by Platane** [comment]
it's fixed :smile: 

the issue was that the vercel was running on node16, where the fetch API is not available

thanks :+1:
