### ISSUE TITLE
Build Failed: Cannot read properties of undefined

### ISSUE THREAD

**Issue by amithm3** [Platane/snk#99]
was running all good before 2 days ago, 
but started getting this build failure:
```
Run Platane/snk/svg-only@v2
🎣 fetching Github user contribution
Error: Action failed with "Cannot read properties of undefined (reading 'split')"
```

**Comment by vikiboss** [comment]
same with me

**Comment by matiastang** [comment]
same

**Comment by ivan-developer-01** [comment]
Everything builds for me...
> ![screenshot](https://github.com/Platane/snk/assets/127977316/afafe496-a83a-4007-8c70-309a3eb6e3c5)

**Comment by matiastang** [comment]
Previously using v2, updated to v3 and adding the environment configuration worked fine.

**Comment by jujimeizuo** [comment]
> Previously using v2, updated to v3 and adding the environment configuration worked fine.

now using v3, getting this build failure，`GITHUB_TOKEN` is bug ???

![image](https://github.com/Platane/snk/assets/61532079/6591a9ba-9ac9-4271-abbc-4d67380d5432)

**Comment by amithm3** [comment]
> Previously using v2, updated to v3 and adding the environment configuration worked fine.

yes worked for me too

**Comment by amithm3** [comment]
@jujimeizuo 

add env to the workflow with `GITHUB_TOKEN`, like in the readme

**Comment by Aman1337g** [comment]
> > Previously using v2, updated to v3 and adding the environment configuration worked fine.
> 
> now using v3, getting this build failure，`GITHUB_TOKEN` is bug ???
> 
> ![image](https://user-images.githubusercontent.com/61532079/273387340-6591a9ba-9ac9-4271-abbc-4d67380d5432.png)

Same Error: Action failed with "Unauthorized" is happening to me.
Here is the Snake.yml file
![Screenshot from 2023-10-07 20-36-40](https://github.com/Platane/snk/assets/97891757/0a00dbca-cbc3-46e5-a480-a8eb42171ad5)

**Comment by jujimeizuo** [comment]
> > > Previously using v2, updated to v3 and adding the environment configuration worked fine.
> > 
> > 
> > now using v3, getting this build failure，`GITHUB_TOKEN` is bug ???
> > ![image](https://user-images.githubusercontent.com/61532079/273387340-6591a9ba-9ac9-4271-abbc-4d67380d5432.png)
> 
> Same Error: Action failed with "Unauthorized" is happening to me. Here is the Snake.yml file ![Screenshot from 2023-10-07 20-36-40](https://user-images.githubusercontent.com/97891757/273393778-0a00dbca-cbc3-46e5-a480-a8eb42171ad5.png)

add `env` in here, then is ok
![image](https://github.com/Platane/snk/assets/61532079/3f684726-19fd-4aba-a777-e87f549c6e6a)

**Comment by Aman1337g** [comment]
Thanks, now it is working 😊

**Comment by Uyouii** [comment]
> Previously using v2, updated to v3 and adding the environment configuration worked fine.

thanks! working now.

**Comment by IOLOII** [comment]
> Previously using v2, updated to v3 and adding the environment configuration worked fine.

![image](https://github.com/Platane/snk/assets/34856171/1c2a797b-dcb8-4b4a-ba5f-4cd4d8e7ce4f)
Fixed! Just change version number 2=>3

**Comment by IOLOII** [comment]
> > > Previously using v2, updated to v3 and adding the environment configuration worked fine.
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/34856171/276614166-1c2a797b-dcb8-4b4a-ba5f-4cd4d8e7ce4f.png) Fixed! Just change version number 2=>3
> 
> 
> 
> thanks! this worked for me

😉
